### ISSUE TITLE
Minimal usable release of crayon.

### ISSUE THREAD

**Issue by shawnscode** [shawnscode/crayon#6]
This is the issue for tracking the progress a minimal usable version of crayon. It should provides some useful and essential facilities to build some simple 2d prototype.

## Current status
With the previous version of v0.0.1, we have a basic graphics sub-system with configurable render pipeline, and a entity-component framework which should works perfectly with [rayon](https://github.com/nikomatsakis/rayon). Its a good but rough start.

## Possible features
- Basic workflow with a simple command line interface (CLI), that could take care of most trivial tasks like resource pre-processing etc.
- Runtime resource management with various basic common types.
- Custom shader language that could be compiled into different versions of GLSL based on target device.
- Primitive draw components, like sprite, mesh, and corresponding renderer.

**Comment by sjaustirni** [comment]
So, what about ECS? If we're going to implement things like scene management or entity serialisation, we should either provide a built-in ECS, or abandon this idea completely, I think. You're also mentioning Prefabs, which play nicely with ECS structure. So that's my random thought about this :-D

**Comment by kaisc** [comment]
Yes! ECS is one of the core features we should supports. An we already have a basic version of ECS placed at [/src/ecs](https://github.com/kaisc/crayon/tree/master/src/ecs), you can checkout the [test cases](https://github.com/kaisc/crayon/blob/master/src/ecs/mod.rs#L39) for details. I'm thinking about building the scene management sub-system based on that, and we can improve the ECS codebase during the development.

**Comment by sjaustirni** [comment]
Oh, I haven't noticed that. Splendid!  :-D

As to the development itself, do we have/want to have a plan in which order we're going to tackle the points mentioned above? If yes, maybe you could open issues with the most urgent points.

I'm asking because even though I do not have too much time this and following week, I could probably get something small done. 

BTW with asset loading we probably could get inspired by ggez. Well, I do not know about the other game libraries, but I was playing with ggez some time ago and they have this long but very convenient piece of code in vfs.rs. But that's just a random thought. :-D

**Comment by kaisc** [comment]
Ah, thats impressive! It's almost the same thing i want to do when abstracting the prototype of  (archive)[https://github.com/kaisc/crayon/blob/master/src/resource/archive.rs] trait. I should definitely do some research of __ggez__ before i start next iteration of asset sub-system.

I'm working on a upcoming game these days, the development of crayon would be started soon in about two weeks. And by the same time. I can do some more research about upcoming features, and make a much more better and detailed plan.
